/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a full install. It is committed here so
// the scaffold is understandable before dependencies are installed.
